#!/usr/bin/env bash

if [ ! -f deps  ]; then
    echo 'deps must be run within its container folder' 1>&2
    exit 1
fi

CURDIR=`pwd`
OLDGOPATH="$GOPATH"
export GOPATH="$CURDIR"

go get github.com/cihub/seelog

export GOPATH="$OLDGOPATH"
echo 'finished'
